"""empty message

Revision ID: 5449a34bbef6
Revises: 3e46a10040ed
Create Date: 2024-11-30 15:27:41.453580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5449a34bbef6'
down_revision = '3e46a10040ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('members', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('members')

    # ### end Alembic commands ###
